version: "3.2"
services:

  backend:
    build:
      context: ./services/backend
      args:
        nodeVersion: ${APP_NODE_VERSION}
        codeRootDirName: ${CODEBASE_ROOT_DIR_NAME}
    entrypoint: /init_script.sh
    privileged: true
    container_name: oss_backend
    volumes:
      - type: bind
        source: ${BACKEND_CODEBASE_HOST_DIR}
        target: /var/www/apps
    links:
      - prisma
    restart: always
    depends_on:
      - oss_pma
    # environment:

  #=========================== DATABASE ===========================

  db:
    image: mysql:5.7
    ports:
      #host:container
      - "${DB_PORT}:3306"
    command: --default-authentication-plugin=mysql_native_password
    container_name: oss_db
    environment:
      MYSQL_DATABASE: ${APP_DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  #=========================== PHPMYADMIN ===========================

  oss_pma:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: oss_pma
    links:
      - db
    ports:
      #host:container
      - ${PMA_PORT}:80
    environment:
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_ROOT_PASSWORD}
      PMA_HOST: db
    depends_on:
      - db

  #=========================== PRISMA ===========================

  prisma:
    image: prismagraphql/prisma:1.34
    container_name: oss_prisma
    restart: always
    links:
      - db
    ports:
    #host:container
      - '${PRISMA_HOST_PORT}:${PRISMA_CONTAINER_PORT}'
    environment:
      PRISMA_CONFIG: |
        port: ${PRISMA_CONTAINER_PORT}
        databases:
          default:
            database: ${APP_DB_NAME}
            connector: mysql
            host: db
            port: ${DB_PORT}
            user: ${DB_ROOT_USER}
            password: ${DB_PASSWORD}
    depends_on:
      - db
      - oss_pma
  
  redis:
    image: redis:5.0.5-alpine
    container_name: ${REDIS_APP_NAME}
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "${REDIS_PORT}:6379"
    environment:
    - REDIS_URL=${REDIS_URL}
# volumes:
#     persistent:
